### PR TITLE
Bug fixes and final changes

### LINKED ISSUE #9: Adding flanking is broken
Flanking wasn't working as intended and instead of adding to end section it actually reduced the end coordinates by the flanking amount.

Changes have been made to fix this in /refactor_branch.

### PR DESCRIPTION
**Pull request by RSWilson1**
Fixed
#9  - Changed to add flanking to end coordinates.
#8 - Fixed errors occurring with GRCh38. Fixed tabix cmd. Using a short version of the long argument in the cmd line still doesn't break but this seems to be argparse functionality rather than an error.
#7 - Removed parameter documentation as no longer needed.

Updated to make bed file zero-based.
Updated Readme with more information and for clarity.
Removed assembly file as no longer needed with new mapping function.
Updated tests for new changes.

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/10)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/10)* status: 6 of 7 files reviewed, 5 unresolved discussions (waiting on @RSWilson1)

___
*[`gene_annotation2bed.py` line 203 at r2](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/10#-Ns7zhjq9DzIYptFX_0R:-Ns7zhjq9DzIYptFX_0S:b-58so6z) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/963f28b3583757c2e0ab0673e3fd215b62acd1ce/gene_annotation2bed.py#L203)):*
> ```Python
>     # print(gff_df[gff_df["source"] == "RefSeq"])
>     # print(gff_df[gff_df["source"] == "BestRefSeq"])
>     # print(gff_df[gff_df["source"] != "BestRefSeq"])
> ```

needed?



_Code quote:_
```Python
    # GFF what to filter on. Select mRNA? or starts with NM_?
    # print(gff_df.head())
    # print(gff_df[gff_df["transcript_id"].str.startswith("NR_")])
    # print(gff_df[gff_df["source"] == "RefSeq"])
    # print(gff_df[gff_df["source"] == "BestRefSeq"])
    # print(gff_df[gff_df["source"] != "BestRefSeq"])
```
___
*[`gene_annotation2bed.py` line 427 at r2](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/10#-Ns8-5YhAk_6Le0vhfnb:-Ns8-5YhAk_6Le0vhfnc:b-nbp6bo) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/963f28b3583757c2e0ab0673e3fd215b62acd1ce/gene_annotation2bed.py#L427)):*
> ```Python
>     gff_df["transcript_id"] = gff_df["transcript_id"].str.split(".").str[0]
>     merged_hgnc_df = gff_df.merge(hgnc_df, on="hgnc_id", how="inner")
>     # check for loss of hgnc ids
> ```

what is the requirement for this? Should you only be printing or raising an exception? 



_Code quote:_
```Python
# check for loss of hgnc ids
```
___
*[`gene_annotation2bed.py` line 714 at r2](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/10#-Ns8-tl45r5vfticwhHa:-Ns8-tl45r5vfticwhHb:bxwnpul) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/963f28b3583757c2e0ab0673e3fd215b62acd1ce/gene_annotation2bed.py#L714)):*
> ```Python
>     -------
>     result : list
>         list of values with flanking added.
> ```

this returns an int and not a list



_Code quote:_
```Python
    result : list
        list of values with flanking added.
```
___
*[`gene_annotation2bed.py` line 733 at r2](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/10#-Ns800FC8PbeYK_yX3-J:-Ns800FC8PbeYK_yX3-K:bxwnpul) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/963f28b3583757c2e0ab0673e3fd215b62acd1ce/gene_annotation2bed.py#L733)):*
> ```Python
>     -------
>     result : list
>         list of values with flanking subtracted, minimum value = 0.
> ```

this returns an int and not a list



_Code quote:_
```Python
    Returns
    -------
    result : list
        list of values with flanking subtracted, minimum value = 0.
```
___
*[`gene_annotation2bed.py` line 813 at r2](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/10#-Ns81A_nAnihtXu-dib0:-Ns81A_nAnihtXu-dib1:b-4vqpo6) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/963f28b3583757c2e0ab0673e3fd215b62acd1ce/gene_annotation2bed.py#L813)):*
> ```Python
>     # Merge the coordinates DataFrame with the BED DataFrame
>     # Set dtypes for the first DataFrame
>     bed_df = bed_df.astype({
> ```

consider where you're setting types to use more strict int types to reduce memory usage, I wrote up a bit in Slack here: https://binfx.slack.com/archives/G01HV61U4BX/p1682010142425769

hgnc_id could probably be `uint16` and coordinates safely can be `uint32`, and genes/transcripts/annotation are likely to be repeated quite a lot using `categorical` type would probably have a decent saving

**Review by RSWilson1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/10)* status: 5 of 9 files reviewed, 5 unresolved discussions (waiting on @jethror1)

___
*[`gene_annotation2bed.py` line 203 at r2](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/10#-Ns7zhjq9DzIYptFX_0R:-Ns82EYX0Q9MDKD3DTyb:buost9k) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/963f28b3583757c2e0ab0673e3fd215b62acd1ce/gene_annotation2bed.py#L203)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

needed?
</blockquote></details>

ahh I knew I forgot something! Will remove as definitely not needed
___
*[`gene_annotation2bed.py` line 714 at r2](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/10#-Ns8-tl45r5vfticwhHa:-NsEMMN3-kLAOMGYj5dO:b-4for5i) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/963f28b3583757c2e0ab0673e3fd215b62acd1ce/gene_annotation2bed.py#L714)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

this returns an int and not a list
</blockquote></details>

corrected.
___
*[`gene_annotation2bed.py` line 733 at r2](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/10#-Ns800FC8PbeYK_yX3-J:-NsEMKSl9JdBicsJGZoe:b-4for5i) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/963f28b3583757c2e0ab0673e3fd215b62acd1ce/gene_annotation2bed.py#L733)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

this returns an int and not a list
</blockquote></details>

corrected.
___
*[`gene_annotation2bed.py` line 813 at r2](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/10#-Ns81A_nAnihtXu-dib0:-NsEMN643hxTYgLz8h5j:b-d02un4) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/963f28b3583757c2e0ab0673e3fd215b62acd1ce/gene_annotation2bed.py#L813)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

consider where you're setting types to use more strict int types to reduce memory usage, I wrote up a bit in Slack here: https://binfx.slack.com/archives/G01HV61U4BX/p1682010142425769

hgnc_id could probably be `uint16` and coordinates safely can be `uint32`, and genes/transcripts/annotation are likely to be repeated quite a lot using `categorical` type would probably have a decent saving
</blockquote></details>

Updated dtypes, some use Int32 as it handles NAs, but as this is downstream of the gff (the point which uses maximum memory) it shouldn't impact the running much.

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/10)* status: 8 of 10 files reviewed, 4 unresolved discussions (waiting on @RSWilson1)

___
*[`gene_annotation2bed.py` line 280 at r3](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/10#-NsEPTcrCxN0EaWEyN0E:-NsEPTcrCxN0EaWEyN0F:b8ja5h5) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/1827ba58918af6c8400f6a33045fab240eb581da/gene_annotation2bed.py#L280)):*
> ```Python
>     coordinates_df['start'] = pd.Series(dtype=np.uint32)
>     coordinates_df['end'] = pd.Series(dtype=np.uint32)
>     coordinates_df['gene'] = ""
> ```

do you not set a type for this column? I assume by default it will either be string or object, would be good to force it to category



_Code quote:_
```Python
coordinates_df['gene'] = ""
```
___
*[`gene_annotation2bed.py` line 827 at r3](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/10#-NsEQ2Z02rc7EsQ2IbB-:-NsEQ2Z02rc7EsQ2IbB0:bgoy27e) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/1827ba58918af6c8400f6a33045fab240eb581da/gene_annotation2bed.py#L827)):*
> ```Python
>         "start_flank": np.uint32,
>         "end_flank": np.uint32,
>         "hgnc_id": "Int32",
> ```

could this not be `uint16`? this would allow for an ID <~60,000 and should half memory usage for the column



_Code quote:_
```Python
"Int32"
```

**Review by RSWilson1 — COMMENTED** [review]
done

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/10#-:-NsEYQ9J6DVOxjlAHbLu:bb7f2mf)* status: 7 of 10 files reviewed, 4 unresolved discussions (waiting on @jethror1 and @RSWilson1)

___
*[`gene_annotation2bed.py` line 427 at r2](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/10#-Ns8-5YhAk_6Le0vhfnb:-NsEXCI-1ai3Uk4CbcSR:bq39g9p) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/963f28b3583757c2e0ab0673e3fd215b62acd1ce/gene_annotation2bed.py#L427)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

what is the requirement for this? Should you only be printing or raising an exception?
</blockquote></details>

So I have changed this to raise an error with the ID needing removing to run again, as otherwise it's kinda a silent fail. I could add a force argument to allow them to continue without removing the ids which might be convenient.
___
*[`gene_annotation2bed.py` line 280 at r3](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/10#-NsEPTcrCxN0EaWEyN0E:-NsEXB6kEeReJ_zRLo60:b-7rl0jd) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/1827ba58918af6c8400f6a33045fab240eb581da/gene_annotation2bed.py#L280)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

do you not set a type for this column? I assume by default it will either be string or object, would be good to force it to category
</blockquote></details>

done.
___
*[`gene_annotation2bed.py` line 827 at r3](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/10#-NsEQ2Z02rc7EsQ2IbB-:-NsEXgs74xmrMez9Ig51:b36cv62) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/1827ba58918af6c8400f6a33045fab240eb581da/gene_annotation2bed.py#L827)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

could this not be `uint16`? this would allow for an ID <~60,000 and should half memory usage for the column
</blockquote></details>

Yep fixed it to work now.

**Review by jethror1 — APPROVED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/10)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RSWilson1)

**Pull request merged**
