### PR TITLE
Initial development

### PR DESCRIPTION
**Pull request by RSWilson1**
This is a script which parses a gff file (refseq) and a tsv containing HGNC_ids and associated annotation. Using this it produced a bed file which is collapses of all the transcripts which match the HGNC ids and an igv html report of the bed file for viewing.

- Uses gff2pandas.py which has been modified to work with dtypes.
- igv_report.py is used for calling create_report from igv_reports to create the the html report of the bed file.
- gene_annotation2bed.py in the main script to run containing the required functions to extract the relevant transcripts and merge overlapping regions in the bed file.

Still to develop:
- Adding columns to html report by using a tsv file + add bed file as additional track with track config.
- Add more tests particularly for edge cases.
- Add handling of transcripts as input.
-  Creating a vcf for testing with VEP.

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/1)

### CODE REVIEW

**Comment by RSWilson1** [comment]
Additional to do:
Write Readme explaining the scripts and requirements.txt.

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/1)* status: 0 of 12 files reviewed, 9 unresolved discussions (waiting on @RSWilson1)

___
*[`gene_annotation2bed.py` line 12 at r1](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/1#-NdBKxi0D0yMrcga51CS:-NdBKxi0D0yMrcga51CT:b-2suosu) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/40d93cd78b2d7b44ef662d5a6f63a8b5042db411/gene_annotation2bed.py#L12)):*
> ```Python
> """
> 
> import argparse
> ```

could you order these imports and split by std lib, 3rd part and local please
___
*[`gene_annotation2bed.py` line 23 at r1](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/1#-NdBNwHX6QDnYECWubos:-NdBNwHX6QDnYECWubot:b1chk06) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/40d93cd78b2d7b44ef662d5a6f63a8b5042db411/gene_annotation2bed.py#L23)):*
> ```Python
> def parse_gff(gff_file):
>     """
>     Summary: Import GFF3 file and convert to pandas DataFrame.
> ```

can you add to the docstring what manipulation of the file is done (i.e. column dropping and transcript filtering), might also be useful to show the structure of the df being returned for clarity



_Code quote:_
```Python
Summary: Import GFF3 file and convert to pandas DataFrame.
```
___
*[`gene_annotation2bed.py` line 74 at r1](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/1#-NdBOCcK257eje8mCene:-NdBOCcK257eje8mCenf:bc6pmcs) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/40d93cd78b2d7b44ef662d5a6f63a8b5042db411/gene_annotation2bed.py#L74)):*
> ```Python
>     dtype_mapping = {
>         'ID': 'str',
>         'transcript_id': 'str',
> ```

what is ID? would either be better as `categorical` types?



_Code quote:_
```Python
        'ID': 'str',
        'transcript_id': 'str',
```
___
*[`gene_annotation2bed.py` line 99 at r1](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/1#-NdBOWU0-FdzAMEBK9Ys:-NdBOWU0-FdzAMEBK9Yt:b-y5rbri) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/40d93cd78b2d7b44ef662d5a6f63a8b5042db411/gene_annotation2bed.py#L99)):*
> ```Python
>     -------
>     int
>         HGNC ID as an integer i.e. 427 for HGNC:427.
> ```

you're also returning None in some conditions, so I'd write this as:
```
Returns
-----------
int | None
    HGNC ID as an integer i.e. 427 for HGNC:427 or None when ...
```



_Suggestion:_
```Python
    int
        HGNC ID as an integer i.e. 427 for HGNC:427.HGNC ID
```
___
*[`gene_annotation2bed.py` line 101 at r1](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/1#-NdBOQJvC97UzpE05DpW:-NdBOQJw4NGQt8lchP1y:b-k11joa) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/40d93cd78b2d7b44ef662d5a6f63a8b5042db411/gene_annotation2bed.py#L101)):*
> ```Python
>         HGNC ID as an integer i.e. 427 for HGNC:427.
>     """
>     if dbxref_str is None:
> ```

`if not dbxref_str:`



_Code quote:_
```Python
    if dbxref_str is None:
```
___
*[`gene_annotation2bed.py` line 110 at r1](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/1#-NdBOn_B5ld8e2n5-WJs:-NdBOn_CClE6qeoxwA_B:b-mqwvey) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/40d93cd78b2d7b44ef662d5a6f63a8b5042db411/gene_annotation2bed.py#L110)):*
> ```Python
>             return int(part.split(':')[-1])
>         elif 'HGNC_' in part:
>             return int(part.split('_')[-1])
> ```

another way to write this more concisely and validate the structure would be:
```
if re.search(r'hgnc[:_][0-9]+', part, re.IGNORECASE):
    return int(part.replace('_', ':').split(':')[-1])
```
would be good to write unit tests for all combinations of IDs to ensure that works as expected



_Code quote:_
```Python
        if 'HGNC:' in part:
            return int(part.split(':')[-1])
        elif 'hgnc:' in part:
            return int(part.split(':')[-1])
        elif 'HGNC_' in part:
            return int(part.split('_')[-1])
```
___
*[`gene_annotation2bed.py` line 137 at r1](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/1#-NdBRN8I9N6UYK596Svy:-NdBRN8I9N6UYK596Svz:b-gefh3h) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/40d93cd78b2d7b44ef662d5a6f63a8b5042db411/gene_annotation2bed.py#L137)):*
> ```Python
>         if chromosome.startswith('na'):
>             continue
>         accession_to_chromosome[accession] = chromosome
> ```

generally want to avoid using `iterrows()` as its about the slowest way to work on a df, consider column wise operations or other serialised functions like:

```
# filter out na from chromosome column and turn accession and chromosome columns to dict
assembly_df = assembly_df[~assembly_df[2].str.startswith('na')]

return dict(zip(assembly_df[6], assembly_df[2]))

```



_Code quote:_
```Python
    for _, row in assembly_df.iterrows():
        chromosome = row[2]
        accession = row[6]
        if chromosome.startswith('na'):
            continue
        accession_to_chromosome[accession] = chromosome
```
___
*[`gene_annotation2bed.py` line 178 at r1](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/1#-NdBTmdG7KV10zPuB-ob:-NdBTmdHDLoF0bYuBm9B:b-iiy92u) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/40d93cd78b2d7b44ef662d5a6f63a8b5042db411/gene_annotation2bed.py#L178)):*
> ```Python
>         Contains only transcripts with NM_ prefix.
>     """
>     gff_df = pd.read_pickle(f"./{pickle_file}")
> ```

 is this f string needed? what happens if the file is in a different dir? 



_Code quote:_
```Python
f"./{pickle_file}"
```
___
*[`gene_annotation2bed.py` line 183 at r1](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/1#-NdBUVmF2J8f_9vXNF9T:-NdBUVmF2J8f_9vXNF9U:b-3wo30e) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/40d93cd78b2d7b44ef662d5a6f63a8b5042db411/gene_annotation2bed.py#L183)):*
> ```Python
> 
> 
> def merge_overlapping(bed_df):
> ```

note for me tomorrow: I do be here



_Code quote:_
```Python
ef merge_overlapping(bed_df):
```

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 7 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/1)* status: 7 of 12 files reviewed, 20 unresolved discussions (waiting on @RSWilson1)

___
*[`gene_annotation2bed.py` line 250 at r1](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/1#-NdElnea-k8ZuThXvfpp:-NdElnea-k8ZuThXvfpq:bnlt2ou) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/40d93cd78b2d7b44ef662d5a6f63a8b5042db411/gene_annotation2bed.py#L250)):*
> ```Python
>     output_file = f"{title}.html"
>     print("Creating IGV report...")
>     print(f"Bed file: {bed_file}, Genome: {genome}, Info columns: {info_columns}, Title: {title}, Output: {output_file}")
> ```

this is a bit long (and probably prints very long), consider breaking it up for prettier printing:
```
print(
    f"Bed file: {bed_file}\nGenome: {genome}\n"
    f"Info columns: {info_columns}\nTitle: {title}\nOutput: {output_file}"
)
```



_Code quote:_
```Python
print(f"Bed file: {bed_file}, Genome: {genome}, Info columns: {info_columns}, Title: {title}, Output: {output_file}")
```
___
*[`gene_annotation2bed.py` line 252 at r1](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/1#-NdEmasO0oKpC-GSStKf:-NdEmasO0oKpC-GSStKg:b-7ytg8b) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/40d93cd78b2d7b44ef662d5a6f63a8b5042db411/gene_annotation2bed.py#L252)):*
> ```Python
>     print(f"Bed file: {bed_file}, Genome: {genome}, Info columns: {info_columns}, Title: {title}, Output: {output_file}")
>     igv.create_igv_report(bed_file, genome, info_columns, title, output_file)
>     return "IGV report created successfully!"
> ```

are you meant to be printing this and not returning?



_Code quote:_
```Python
    return "IGV report created successfully!"
```
___
*[`gene_annotation2bed.py` line 256 at r1](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/1#-NdEnN7J-SmMizvZCCTU:-NdEnN7J-SmMizvZCCTV:b-cr7vxy) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/40d93cd78b2d7b44ef662d5a6f63a8b5042db411/gene_annotation2bed.py#L256)):*
> ```Python
> 
> def main():
>     parser = argparse.ArgumentParser(description="GFF Processing Script")
> ```

its kinda personal preference but I would consider adding your args to their own function, it can be cleaner when it gets larger and if you want to add any additional code for validating inputs etc, some examples:
- https://github.com/eastgenomics/eggd_conductor/blob/262d9abcd20bf141a92d9f59fe3498cfe48d0dc7/resources/home/dnanexus/run_workflows/run_workflows.py#L264
- https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/4b914db6963b179b31bc28f93b24c7c889b6445f/resources/home/dnanexus/generate_workbook/generate_workbook.py#L13
___
*[`gene_annotation2bed.py` line 274 at r1](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/1#-NdEoEwc4QQdpRHUr9Mj:-NdEoEwc4QQdpRHUr9Mk:b9gp97a) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/40d93cd78b2d7b44ef662d5a6f63a8b5042db411/gene_annotation2bed.py#L274)):*
> ```Python
> 
>     # read in pickle file if provided
>     if args.pickle is not None:
> ```

can just be `if args.pickle`



_Code quote:_
```Python
if args.pickle is not None:
```
___
*[`gene_annotation2bed.py` line 285 at r1](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/1#-NdEoNy-DZASA0Kq1Rr4:-NdEoNy-DZASA0Kq1Rr5:bq9y4s9) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/40d93cd78b2d7b44ef662d5a6f63a8b5042db411/gene_annotation2bed.py#L285)):*
> ```Python
>         annotation_df = pd.read_csv(args.annotation_file, sep="\t")
>     # Read the transcript annotation file
>     elif args.transcript_file is not None:
> ```

same as above for the Nones



_Code quote:_
```Python
    if args.annotation_file is not None:
        annotation_df = pd.read_csv(args.annotation_file, sep="\t")
    # Read the transcript annotation file
    elif args.transcript_file is not None:
```
___
*[`gene_annotation2bed.py` line 288 at r1](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/1#-NdEoSESBhPNK7MfCvbm:-NdEoSESBhPNK7MfCvbn:bgsaid1) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/40d93cd78b2d7b44ef662d5a6f63a8b5042db411/gene_annotation2bed.py#L288)):*
> ```Python
>         annotation_df = pd.read_csv(args.transcript_file, sep="\t")
>     else:
>         SystemExit("Please provide an annotation file")
> ```

don't think this is needed since you nicely handled it above with required mutually exclusive groups



_Code quote:_
```Python
    else:
        SystemExit("Please provide an annotation file")
```
___
*[`gene_annotation2bed.py` line 323 at r1](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/1#-NdEoxQa2l6tKfyrfD3p:-NdEoxQa2l6tKfyrfD3q:br6cnu8) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/40d93cd78b2d7b44ef662d5a6f63a8b5042db411/gene_annotation2bed.py#L323)):*
> ```Python
>     # Write the collapsed data to an output file
>     output_file_name = f"output_{args.reference_genome}" \
>                        f"_{args.output_file_suffix}.maf"
> ```

multi line strings are nicer in parentheses (and then this can just be one too I think for length):
```
    output_file_name = (
        f"output_{args.reference_genome}_{args.output_file_suffix}.maf"
    )
```



_Code quote:_
```Python
    output_file_name = f"output_{args.reference_genome}" \
                       f"_{args.output_file_suffix}.maf"
```
___
*[`igv_report.py` line 27 at r1](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/1#-NdEpUc0BA24zyUbvpIG:-NdEpUc0BA24zyUbvpIH:b-k9qnx3) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/40d93cd78b2d7b44ef662d5a6f63a8b5042db411/igv_report.py#L27)):*
> ```Python
>         "create_report",
>         bed_file,
>         "--fasta", "/home/rswilson1/Documents/MSC_dissertation/MELT_example_data/hs37d5.fa",
> ```

this wants to be an input



_Code quote:_
```Python
     "--fasta", "/home/rswilson1/Documents/MSC_dissertation/MELT_example_data/hs37d5.fa",
```
___
*[`TracksConfig.json` line 1 at r1](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/1#-NdEpdub3krdC_oVlOSE:-NdEpduc2WPng0ifZ3I-:b-1kpbd9) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/40d93cd78b2d7b44ef662d5a6f63a8b5042db411/TracksConfig.json#L1)):*
> ```JSON
> [
> ```

 whats this config for an why is it only 38? do you need an input of build no to specify to igv reports?
___
*[`tests/test_attributes_extraction.py` line 5 at r1](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/1#-NdEptaGB4gNggxmeY74:-NdEptaGB4gNggxmeY75:bjp365w) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/40d93cd78b2d7b44ef662d5a6f63a8b5042db411/tests/test_attributes_extraction.py#L5)):*
> ```Python
> sys.path.append('../gene_annotation2bed')
> from gene_annotation2bed import extract_hgnc_id
> ```

can you add simple docstrings for what is being tested and why (i.e. use cases of errors / data formats you're trying to pick up) as this can help with understanding what is being caught (maybe with minimal data structure examples too)
___
*[`tests/test_gff_parsing.py` line 12 at r1](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/1#-NdEq8dq4BUVeii0v3b6:-NdEq8dr1q4N0ubgfMuJ:bmwfpe8) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/40d93cd78b2d7b44ef662d5a6f63a8b5042db411/tests/test_gff_parsing.py#L12)):*
> ```Python
> pd.set_option('display.width', 150)
> 
> class Test_parsing_gff(unittest.TestCase):
> ```

doc strings as above please

**Review by RSWilson1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/1)* status: 6 of 15 files reviewed, 20 unresolved discussions (waiting on @jethror1 and @RSWilson1)

___
*[`gene_annotation2bed.py` line 12 at r1](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/1#-NdBKxi0D0yMrcga51CS:-NdkL-9z-lGzU2wP5BeZ:bb7f2mf) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/40d93cd78b2d7b44ef662d5a6f63a8b5042db411/gene_annotation2bed.py#L12)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

could you order these imports and split by std lib, 3rd part and local please
</blockquote></details>

done
___
*[`gene_annotation2bed.py` line 23 at r1](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/1#-NdBNwHX6QDnYECWubos:-NdjAa-D4CW-amI3DDmL:b-cen1i) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/40d93cd78b2d7b44ef662d5a6f63a8b5042db411/gene_annotation2bed.py#L23)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

can you add to the docstring what manipulation of the file is done (i.e. column dropping and transcript filtering), might also be useful to show the structure of the df being returned for clarity
</blockquote></details>

added to the docstring
___
*[`gene_annotation2bed.py` line 74 at r1](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/1#-NdBOCcK257eje8mCene:-NdjB-MVA4meNVclyNYX:b-ou9nbx) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/40d93cd78b2d7b44ef662d5a6f63a8b5042db411/gene_annotation2bed.py#L74)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

what is ID? would either be better as `categorical` types?
</blockquote></details>

ID and transcript_id are unique and not repeated so I think str would be better for both?
___
*[`gene_annotation2bed.py` line 99 at r1](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/1#-NdBOWU0-FdzAMEBK9Ys:-NdjBK-S5_55vhYTLHf3:b-896fix) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/40d93cd78b2d7b44ef662d5a6f63a8b5042db411/gene_annotation2bed.py#L99)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

you're also returning None in some conditions, so I'd write this as:
```
Returns
-----------
int | None
    HGNC ID as an integer i.e. 427 for HGNC:427 or None when ...
```
</blockquote></details>

Done.
___
*[`gene_annotation2bed.py` line 101 at r1](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/1#-NdBOQJvC97UzpE05DpW:-NdjBLto3eWLkrChjvcW:b-896fix) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/40d93cd78b2d7b44ef662d5a6f63a8b5042db411/gene_annotation2bed.py#L101)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

`if not dbxref_str:`
</blockquote></details>

Done.
___
*[`gene_annotation2bed.py` line 110 at r1](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/1#-NdBOn_B5ld8e2n5-WJs:-NdjBMvH5Xc_-goDXQ_r:b-896fix) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/40d93cd78b2d7b44ef662d5a6f63a8b5042db411/gene_annotation2bed.py#L110)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

another way to write this more concisely and validate the structure would be:
```
if re.search(r'hgnc[:_][0-9]+', part, re.IGNORECASE):
    return int(part.replace('_', ':').split(':')[-1])
```
would be good to write unit tests for all combinations of IDs to ensure that works as expected
</blockquote></details>

Done.
___
*[`gene_annotation2bed.py` line 137 at r1](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/1#-NdBRN8I9N6UYK596Svy:-NdVTiij0jcssJmu6PjP:bg8d09x) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/40d93cd78b2d7b44ef662d5a6f63a8b5042db411/gene_annotation2bed.py#L137)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

generally want to avoid using `iterrows()` as its about the slowest way to work on a df, consider column wise operations or other serialised functions like:

```
# filter out na from chromosome column and turn accession and chromosome columns to dict
assembly_df = assembly_df[~assembly_df[2].str.startswith('na')]

return dict(zip(assembly_df[6], assembly_df[2]))

```
</blockquote></details>

yep :+1: 
___
*[`gene_annotation2bed.py` line 178 at r1](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/1#-NdBTmdG7KV10zPuB-ob:-NdVTgntEkEY6ukyJmlC:bpl43mb) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/40d93cd78b2d7b44ef662d5a6f63a8b5042db411/gene_annotation2bed.py#L178)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

is this f string needed? what happens if the file is in a different dir?
</blockquote></details>

nope removed.
___
*[`gene_annotation2bed.py` line 183 at r1](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/1#-NdBUVmF2J8f_9vXNF9T:-NdkL1LR8ks1OeOnAozl:b-896fix) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/40d93cd78b2d7b44ef662d5a6f63a8b5042db411/gene_annotation2bed.py#L183)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

note for me tomorrow: I do be here
</blockquote></details>

Done.
___
*[`gene_annotation2bed.py` line 250 at r1](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/1#-NdElnea-k8ZuThXvfpp:-NdVTpNSAxgIWd1BYIv3:bb6mt9b) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/40d93cd78b2d7b44ef662d5a6f63a8b5042db411/gene_annotation2bed.py#L250)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

this is a bit long (and probably prints very long), consider breaking it up for prettier printing:
```
print(
    f"Bed file: {bed_file}\nGenome: {genome}\n"
    f"Info columns: {info_columns}\nTitle: {title}\nOutput: {output_file}"
)
```
</blockquote></details>

:+1:
___
*[`gene_annotation2bed.py` line 252 at r1](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/1#-NdEmasO0oKpC-GSStKf:-NdVlHsC0vMPvmAeCs_Z:bb7s9zz) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/40d93cd78b2d7b44ef662d5a6f63a8b5042db411/gene_annotation2bed.py#L252)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

are you meant to be printing this and not returning?
</blockquote></details>

yes!
___
*[`gene_annotation2bed.py` line 256 at r1](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/1#-NdEnN7J-SmMizvZCCTU:-NdkL2po-1-5kCMIOr5I:bb7f2mf) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/40d93cd78b2d7b44ef662d5a6f63a8b5042db411/gene_annotation2bed.py#L256)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

its kinda personal preference but I would consider adding your args to their own function, it can be cleaner when it gets larger and if you want to add any additional code for validating inputs etc, some examples:
- https://github.com/eastgenomics/eggd_conductor/blob/262d9abcd20bf141a92d9f59fe3498cfe48d0dc7/resources/home/dnanexus/run_workflows/run_workflows.py#L264
- https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/4b914db6963b179b31bc28f93b24c7c889b6445f/resources/home/dnanexus/generate_workbook/generate_workbook.py#L13
</blockquote></details>

done
___
*[`gene_annotation2bed.py` line 274 at r1](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/1#-NdEoEwc4QQdpRHUr9Mj:-NdVpnl947o0FXefVJJi:bb7f2mf) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/40d93cd78b2d7b44ef662d5a6f63a8b5042db411/gene_annotation2bed.py#L274)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

can just be `if args.pickle`
</blockquote></details>

done
___
*[`gene_annotation2bed.py` line 285 at r1](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/1#-NdEoNy-DZASA0Kq1Rr4:-NdZFEpD7QTIIAr9Yezz:bb6un1j) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/40d93cd78b2d7b44ef662d5a6f63a8b5042db411/gene_annotation2bed.py#L285)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

same as above for the Nones
</blockquote></details>

Done
___
*[`gene_annotation2bed.py` line 288 at r1](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/1#-NdEoSESBhPNK7MfCvbm:-NdZFQxdCOkrT-JO955w:b829rca) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/40d93cd78b2d7b44ef662d5a6f63a8b5042db411/gene_annotation2bed.py#L288)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

don't think this is needed since you nicely handled it above with required mutually exclusive groups
</blockquote></details>

Nice, removed
___
*[`gene_annotation2bed.py` line 323 at r1](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/1#-NdEoxQa2l6tKfyrfD3p:-NdUzi7Q5Uc3xpB5Z7Tc:bb7f2mf) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/40d93cd78b2d7b44ef662d5a6f63a8b5042db411/gene_annotation2bed.py#L323)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

multi line strings are nicer in parentheses (and then this can just be one too I think for length):
```
    output_file_name = (
        f"output_{args.reference_genome}_{args.output_file_suffix}.maf"
    )
```
</blockquote></details>

done
___
*[`igv_report.py` line 27 at r1](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/1#-NdEpUc0BA24zyUbvpIG:-NdkL5UgCNcvAEAUxpnW:b-ok8etr) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/40d93cd78b2d7b44ef662d5a6f63a8b5042db411/igv_report.py#L27)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

this wants to be an input
</blockquote></details>

done, maybe need to rethink what should be provided and use default data for genomes provided? But would require large files to be stored so maybe not feasible?
___
*[`tests/test_attributes_extraction.py` line 5 at r1](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/1#-NdEptaGB4gNggxmeY74:-NdkLHdPAgYZSCryW5Tl:bb7f2mf) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/40d93cd78b2d7b44ef662d5a6f63a8b5042db411/tests/test_attributes_extraction.py#L5)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

can you add simple docstrings for what is being tested and why (i.e. use cases of errors / data formats you're trying to pick up) as this can help with understanding what is being caught (maybe with minimal data structure examples too)
</blockquote></details>

done
___
*[`tests/test_gff_parsing.py` line 12 at r1](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/1#-NdEq8dq4BUVeii0v3b6:-NdkLIm0BA9XjfhfwwMU:bbrd7g9) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/40d93cd78b2d7b44ef662d5a6f63a8b5042db411/tests/test_gff_parsing.py#L12)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

doc strings as above please
</blockquote></details>

done need to add more tests for next version
___
*[`TracksConfig.json` line 1 at r1](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/1#-NdEpdub3krdC_oVlOSE:-NdkLMJWCNBGyeAfhxqO:biic33y) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/40d93cd78b2d7b44ef662d5a6f63a8b5042db411/TracksConfig.json#L1)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

whats this config for an why is it only 38? do you need an input of build no to specify to igv reports?
</blockquote></details>

removed and generated in script using a string and variables provided.

**Review by jethror1 — APPROVED** [review]
:lgtm:

> Reviewed 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/1#-:-NdoWGxyDevn5Cu1FtNr:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @RSWilson1)

___
*[`gene_annotation2bed.py` line 23 at r1](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/1#-NdBNwHX6QDnYECWubos:-NdoUnpx2kHEuXc_AIF9:bikt9qr) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/40d93cd78b2d7b44ef662d5a6f63a8b5042db411/gene_annotation2bed.py#L23)):*
<details><summary><i>Previously, RSWilson1 (Robert Wilson) wrote…</i></summary><blockquote>

added to the docstring
</blockquote></details>

what a beautiful docstring 10/10

**Review by jethror1 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/1#-:-NdoWQXfC6_wPVScEziX:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @RSWilson1)

**Review by jethror1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RSWilson1)

**Pull request merged**
