### PR TITLE
Added transcripts and coordinates as accepted inputs in the TSV file.

### PR DESCRIPTION
**Pull request by RSWilson1**
PR changes:

- Added transcripts and coordinates as accepted inputs
- Added initial draft for constructing VCF for testing bed annotation with VEP.
- Made some formatting and clarity changes
- Moved creation of bed file into it's own function.
- Created function to convert coordinates from TSV into bed format.
- Added unit tests

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/2)

### CODE REVIEW

**Review by RSWilson1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/2)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @jethror1)

___
*[`gene_annotation2bed.py` line 271 at r1](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/2#-NeMwbPk2gJvGdw1mgeI:-NeMwbPk2gJvGdw1mgeJ:bvha22w) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/457e0716df1ebef4b2a721143094a8c91f31b4f8/gene_annotation2bed.py#L271)):*
> ```Python
> 
> def parse_annotation_tsv(path: str,
>                          gff_transcripts_df: pd.DataFrame) -> tuple[pd.DataFrame,
> ```

Is there a better way to split up lines like this?

**Review by RSWilson1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/2)* status: 0 of 11 files reviewed, 3 unresolved discussions (waiting on @jethror1)

___
*[`construct_vcf.py` line 111 at r1](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/2#-NeN2Ck56fPPMxruFPl2:-NeN2Ck56fPPMxruFPl3:bckka55) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/457e0716df1ebef4b2a721143094a8c91f31b4f8/construct_vcf.py#L111)):*
> ```Python
>     # Initialize an empty list to store the rows of the output dataframe
>     rows = []
>     reference_path = "/home/rswilson1/Documents/MSC_dissertation/MELT_example_data/hs37d5.fa"
> ```

remove hard-coded path
___
*[`construct_vcf.py` line 145 at r1](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/2#-NeN2GeVDiJfhGyCR9hI:-NeN2GeVDiJfhGyCR9hJ:byt1thd) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/457e0716df1ebef4b2a721143094a8c91f31b4f8/construct_vcf.py#L145)):*
> ```Python
>     output_df.to_csv('test.vcf', sep="\t", index=False)
> 
>     # test_vcf_cancer_TSG_V4.vcf -- 0-based coordinates
> ```

removed old comment

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/2)* status: 2 of 12 files reviewed, 8 unresolved discussions (waiting on @RSWilson1)

___
*[`construct_vcf.py` line 32 at r1](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/2#-NeNWXx21v0DXaW44hZa:-NeNWXx3AIb64mokPU21:b-8nqkop) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/457e0716df1ebef4b2a721143094a8c91f31b4f8/construct_vcf.py#L32)):*
> ```Python
>     row (pandas.Series): A row of a pandas dataframe containing the chromosome,
>     start, and end positions of the nucleotide sequence to fetch.
> ```

missing input from params
___
*[`construct_vcf.py` line 111 at r1](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/2#-NeN2Ck56fPPMxruFPl2:-NeNWirh8r_10U-WU55s:b-t77xc3) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/457e0716df1ebef4b2a721143094a8c91f31b4f8/construct_vcf.py#L111)):*
<details><summary><i>Previously, RSWilson1 (Robert Wilson) wrote…</i></summary><blockquote>

remove hard-coded path
</blockquote></details>

agreed
___
*[`construct_vcf.py` line 119 at r1](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/2#-NeNgwjo8QWMmaf_tpwJ:-NeNgwjpBK7aS2sc4qmY:b-2wem28) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/457e0716df1ebef4b2a721143094a8c91f31b4f8/construct_vcf.py#L119)):*
I'm confused here why for every row in the bed file you loop over the whole `seq_df`?

also using iterrows isn't ideal, particularly nesting it as it will be quite slow. For the first part you could call that function without iterating like:

```
>>> df
   a
0  1
1  2
2  3
>>> def multiply(x):
...     return x*2
... 

>>> df['b'] = df.apply(lambda x: multiply(x))
>>> df
   a  b
0  1  2
1  2  4
2  3  6
```



_Code quote:_
```Python
    for i, row in bed_file.iterrows():
        # Fetch the nucleotide sequence from NCBI using the fetch_nucleotides function
        seq_df = fetch_nucleotides(row, reference_path)
        # Iterate through the rows of the seq_df to create the output dataframe rows
        for j, seq_row in seq_df.iterrows():
            # Define the output dataframe row as a dictionary
```
___
*[`gene_annotation2bed.py` line 248 at r1](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/2#-NeNlNOtAFj7vH453CkR:-NeNlNOtAFj7vH453CkS:bo8j4im) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/457e0716df1ebef4b2a721143094a8c91f31b4f8/gene_annotation2bed.py#L248)):*
> ```Python
>         ].str.split("[:-]", expand=True)
>         coordinates_df["chromosome"] = coordinates_df["chromosome"].str.replace(
>             r"(?i)chr(omosome)?", "", regex=True
> ```

nice, I didn't know the replace for pandas supported regex



_Code quote:_
```Python
            r"(?i)chr(omosome)?", "", regex=True
```
___
*[`gene_annotation2bed.py` line 575 at r1](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/2#-NeNlpqc6i2_GLZTCeTy:-NeNlpqc6i2_GLZTCeTz:b3pxdx9) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/457e0716df1ebef4b2a721143094a8c91f31b4f8/gene_annotation2bed.py#L575)):*
> ```Python
>     Returns
>     -------
>     None
> ```

minor thing but where a function doesn't have params or return anything I'd just omit it from the docstring, and I also like to extend it where it writes files with an `Outputs` 

https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/4b914db6963b179b31bc28f93b24c7c889b6445f/resources/home/dnanexus/generate_workbook/utils/excel.py#L52

I also like to add where a function explicitly may raise errors too to speed up debugging from reading back through code like:

https://github.com/eastgenomics/eggd_generate_variant_workbook/blob/4b914db6963b179b31bc28f93b24c7c889b6445f/resources/home/dnanexus/generate_workbook/utils/filters.py#L47



_Code quote:_
```Python
    Returns
    -------
    None
```
___
*[`gff2pandas.py` line 37 at r1](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/2#-NeNmd-j93S_d43tk1PB:-NeNmd-j93S_d43tk1PC:b-uobek3) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/457e0716df1ebef4b2a721143094a8c91f31b4f8/gff2pandas.py#L37)):*
> ```Python
> def _split_atts(atts):
>     """Split a feature string into attributes."""
>     if atts is None:
> ```

`if not atts:`



_Code quote:_
```Python
if atts is None:
```

**Review by jethror1 — COMMENTED** [review]
> Reviewed 3 of 11 files at r1, 1 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/2)* status: 6 of 12 files reviewed, 5 unresolved discussions (waiting on @RSWilson1)

**Review by RSWilson1 — COMMENTED** [review]
resolved super long lines, and module level imports are due to use sys to import them.

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/2#-:-Ngxqn5H3qORTUvbQ0C0:bo7sptx)* status: 6 of 12 files reviewed, 3 unresolved discussions (waiting on @jethror1 and @RSWilson1)

___
*[`construct_vcf.py` line 32 at r1](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/2#-NeNWXx21v0DXaW44hZa:-NgwWkkA9LKvD-O9RNXA:b-t948zx) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/457e0716df1ebef4b2a721143094a8c91f31b4f8/construct_vcf.py#L32)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

missing input from params
</blockquote></details>

added.
___
*[`construct_vcf.py` line 111 at r1](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/2#-NeN2Ck56fPPMxruFPl2:-NgwZzBu5E3Ag5LS_2ut:bb7f2mf) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/457e0716df1ebef4b2a721143094a8c91f31b4f8/construct_vcf.py#L111)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

agreed
</blockquote></details>

done
___
*[`construct_vcf.py` line 119 at r1](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/2#-NeNgwjo8QWMmaf_tpwJ:-Ngxm2nQ5cRF24LtKVN7:b-xfb6f5) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/457e0716df1ebef4b2a721143094a8c91f31b4f8/construct_vcf.py#L119)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

I'm confused here why for every row in the bed file you loop over the whole `seq_df`?

also using iterrows isn't ideal, particularly nesting it as it will be quite slow. For the first part you could call that function without iterating like:

```
>>> df
   a
0  1
1  2
2  3
>>> def multiply(x):
...     return x*2
... 

>>> df['b'] = df.apply(lambda x: multiply(x))
>>> df
   a  b
0  1  2
1  2  4
2  3  6
```
</blockquote></details>

changed this to use a single for loop, would apply work for this to not use iterrows if I am using pd.concat?
___
*[`gene_annotation2bed.py` line 248 at r1](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/2#-NeNlNOtAFj7vH453CkR:-NgxAcbdBsDX0d5Cht2y:b4c9lyr) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/457e0716df1ebef4b2a721143094a8c91f31b4f8/gene_annotation2bed.py#L248)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

nice, I didn't know the replace for pandas supported regex
</blockquote></details>

:thumbsup: 
___
*[`gff2pandas.py` line 37 at r1](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/2#-NeNmd-j93S_d43tk1PB:-Ngx7xGj0GmzJCyzSFtX:b-896fix) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/457e0716df1ebef4b2a721143094a8c91f31b4f8/gff2pandas.py#L37)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

`if not atts:`
</blockquote></details>

Done.

**Review by jethror1 — COMMENTED** [review]
> Reviewed 1 of 11 files at r1, 1 of 4 files at r3, 3 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/2)* status: 11 of 12 files reviewed, 1 unresolved discussion (waiting on @RSWilson1)

___
*[`gene_annotation2bed.py` line 271 at r1](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/2#-NeMwbPk2gJvGdw1mgeI:-NgxtvtF2cOTa_nu4Tfj:b-a1kbji) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/457e0716df1ebef4b2a721143094a8c91f31b4f8/gene_annotation2bed.py#L271)):*
<details><summary><i>Previously, RSWilson1 (Robert Wilson) wrote…</i></summary><blockquote>

Is there a better way to split up lines like this?
</blockquote></details>

what is this comment referring to? I think it might have shifted

**Review by RSWilson1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/2)* status: 11 of 12 files reviewed, 1 unresolved discussion (waiting on @jethror1 and @RSWilson1)

___
*[`gene_annotation2bed.py` line 271 at r1](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/2#-NeMwbPk2gJvGdw1mgeI:-Ngxv-2BBakAb22VcASj:btu9rey) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/457e0716df1ebef4b2a721143094a8c91f31b4f8/gene_annotation2bed.py#L271)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

what is this comment referring to? I think it might have shifted
</blockquote></details>

I should have been clearer, for the def function line, is there a best practice for splitting them over multiple lines different to how I currently have done this?

**Review by jethror1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/2)* status: 11 of 12 files reviewed, 1 unresolved discussion (waiting on @RSWilson1)

___
*[`gene_annotation2bed.py` line 271 at r1](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/2#-NeMwbPk2gJvGdw1mgeI:-Ngxz5AMEnTiEPJZ81xt:b-esa49s) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/457e0716df1ebef4b2a721143094a8c91f31b4f8/gene_annotation2bed.py#L271)):*
<details><summary><i>Previously, RSWilson1 (Robert Wilson) wrote…</i></summary><blockquote>

I should have been clearer, for the def function line, is there a best practice for splitting them over multiple lines different to how I currently have done this?
</blockquote></details>

ahh okay, I like to format like this when it gets long from lots of inputs: https://github.com/eastgenomics/dias_batch_running/blob/062c51f27183de16166354a195d3de206413e7e1/resources/home/dnanexus/dias_batch/utils/dx_requests.py#L718

**Review by jethror1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/2)* status: 11 of 12 files reviewed, all discussions resolved (waiting on @RSWilson1)

**Pull request merged**
