### PR TITLE
Refactor branch

### PR DESCRIPTION
**Pull request by RSWilson1**
### PR for refactoring

- Re-organised scripts into subfolders scripts and utils.
- Split-out a large function in gene_annotation2bed.py
- Updated tests to reflect changes
- Added some tests for functions in gene_annotation2bed.py
  - write_bed function
  - merge_overlapping function
  - subtract_and_replace function

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/4)

### CODE REVIEW

**Review by RSWilson1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/4)* status: 0 of 19 files reviewed, 2 unresolved discussions (waiting on @jethror1)

___
*[`README.md` line 96 at r1](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/4#-Np5L-Uu72vR_xrxsiPq:-Np5L-Uu72vR_xrxsiPr:b14o7cd) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/17446c91a4aea2ad12a28620f53547edd41aa5e0/README.md#L96)):*
> ```Markdown
> 
> 
> ## Strucute of code
> ```

I like file trees but not sure if this is useful so might remove.
___
*[`tests/test_gene_annotation2bed.py` line 24 at r1](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/4#-Np5LBeU5sURN1qItdTp:-Np5LBeU5sURN1qItdTq:b-bwxkn1) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/17446c91a4aea2ad12a28620f53547edd41aa5e0/tests/test_gene_annotation2bed.py#L24)):*
> ```Python
> sys.path.append('../gene_annotation2bed')
> 
> from gene_annotation2bed import (convert_coordinates, extract_hgnc_id,
> ```

When I get to this, would it be better to just use import * or should I always avoid that as it's not pythonic

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 15 of 19 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/4)* status: 15 of 19 files reviewed, 7 unresolved discussions (waiting on @RSWilson1)

___
*[`README.md` line 96 at r1](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/4#-Np5L-Uu72vR_xrxsiPq:-NpLpJoMELDATUGqs6VH:bw4egj8) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/17446c91a4aea2ad12a28620f53547edd41aa5e0/README.md#L96)):*
<details><summary><i>Previously, RSWilson1 (Robert Wilson) wrote…</i></summary><blockquote>

I like file trees but not sure if this is useful so might remove.
</blockquote></details>

did you remove something here?
___
*[`README.md` line 33 at r2](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/4#-NpLoypM6EKmN1eMOo3B:-NpLoypM6EKmN1eMOo3C:b-ctt82h) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/3f77e25e2e17e2b2d665e25b95a2dc099dc79314/README.md#L33)):*
> ```Markdown
> 
> ### Required
> - `-ig`, `--annotation_file` (`str`): Path to the annotation file (TSV), this file is essential for the app to execute successfully.
> ```

why `-ig`?



_Code quote:_
```Markdown
-ig`
```
___
*[`README.md` line 36 at r2](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/4#-NpLp4vgCx2bIWjUNlKG:-NpLp4vgCx2bIWjUNlKH:b-uhb8mh) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/3f77e25e2e17e2b2d665e25b95a2dc099dc79314/README.md#L36)):*
> ```Markdown
> - `-o`, `output` (`str`): Output file suffix, required for specifying the suffix for the generated output files.
> - `-build`, `--genome_build` (`str`): Reference genome build (hg19/hg38), choose either 'hg19' or 'hg38' based on your requirements.
> - `-f`, `--flanking` (`int`): Flanking size, an integer value representing the size of flanking regions for each gene, transcript or coordinates provided.
> ```

should this be optional and default to zero?



_Code quote:_
```Markdown
 `-f`, `--flanking` (`int`): Flanking size, an integer value representing the size of flanking regions for each gene, transcript or coordinates provided.
```
___
*[`tests/test_gene_annotation2bed.py` line 24 at r1](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/4#-Np5LBeU5sURN1qItdTp:-NpLpQz7-41CHgLpy79k:b-py0e2t) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/17446c91a4aea2ad12a28620f53547edd41aa5e0/tests/test_gene_annotation2bed.py#L24)):*
<details><summary><i>Previously, RSWilson1 (Robert Wilson) wrote…</i></summary><blockquote>

When I get to this, would it be better to just use import * or should I always avoid that as it's not pythonic
</blockquote></details>

generally avoiud this as it can cause you to pollute the namespace and can cause collisions (i.e. if 2 packages have a methodw named the same, the 2nd `import *` will silently override the first import). Additionally, it causes everything to be imported which can be slow if it's a big package, and you add in more ambiguity from where something is imported from (vs doing something like `from unittest imort TestCase`, where you know exactly where `TestCase` has come from).

Alternatively, if you have a lot to import it can be easier to go with `import gene_annotation2bed as bed` or similar, then reference everything as `bed.convert_coordinates`
___
*[`tests/test_gene_annotation2bed.py` line 189 at r2](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/4#-NpLqsYU1Wh5l_LArj-u:-NpLqsYVDGDmtT44lABz:b-88ethh) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/3f77e25e2e17e2b2d665e25b95a2dc099dc79314/tests/test_gene_annotation2bed.py#L189)):*
> ```Python
>         """
>         # Set-up to capture stdout
>         capturedOutput = StringIO()
> ```

I thiiiiink using `capsys` for capturing stdout / stderr in tests is more robust (although I dont remember where I read a good explanation but this is a good start: https://docs.pytest.org/en/7.1.x/how-to/capture-stdout-stderr.html )
___
*[`tests/test_gene_annotation2bed.py` line 218 at r2](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/4#-NpLr8gZAecANW9Scj5t:-NpLr8gZAecANW9Scj5u:b-4p5qg3) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/3f77e25e2e17e2b2d665e25b95a2dc099dc79314/tests/test_gene_annotation2bed.py#L218)):*
> ```Python
>         test no pandas import as empty file.
>         """
>         expected_output = (
> ```

you don't actually use this, should it be in the `self.assertRaises`?



_Code quote:_
```Python
expected_output
```
___
*[`tests/test_igv_report.py` line 5 at r2](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/4#-NpLrWAb0SGCqdqVF1_P:-NpLrWAb0SGCqdqVF1_Q:beg1da9) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/3f77e25e2e17e2b2d665e25b95a2dc099dc79314/tests/test_igv_report.py#L5)):*
> ```Python
> """
> from scripts import igv_report
> ```

is this still needed?

**Review by RSWilson1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/4)* status: 12 of 22 files reviewed, 7 unresolved discussions (waiting on @jethror1 and @RSWilson1)

___
*[`README.md` line 96 at r1](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/4#-Np5L-Uu72vR_xrxsiPq:-NpP6CdpE7cSyh5FJgj9:b-vd3jps) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/17446c91a4aea2ad12a28620f53547edd41aa5e0/README.md#L96)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

did you remove something here?
</blockquote></details>

yep I decided to remove it.
___
*[`README.md` line 33 at r2](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/4#-NpLoypM6EKmN1eMOo3B:-NpZMlITDhsVhJxgXbQo:bdxb5rs) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/3f77e25e2e17e2b2d665e25b95a2dc099dc79314/README.md#L33)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

why `-ig`?
</blockquote></details>

yeah I was trying to come up with a better shorthand, don't know why I left it as ig, changed now to -ann.
___
*[`README.md` line 36 at r2](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/4#-NpLp4vgCx2bIWjUNlKG:-NpZMubU5AFokI4eyg8K:bp1muxz) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/3f77e25e2e17e2b2d665e25b95a2dc099dc79314/README.md#L36)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

should this be optional and default to zero?
</blockquote></details>

yep changed to default to 0 and optional.
___
*[`tests/test_gene_annotation2bed.py` line 24 at r1](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/4#-Np5LBeU5sURN1qItdTp:-NpZMyUQ3PvMQOmF58iB:b3gvcxb) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/17446c91a4aea2ad12a28620f53547edd41aa5e0/tests/test_gene_annotation2bed.py#L24)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

generally avoiud this as it can cause you to pollute the namespace and can cause collisions (i.e. if 2 packages have a methodw named the same, the 2nd `import *` will silently override the first import). Additionally, it causes everything to be imported which can be slow if it's a big package, and you add in more ambiguity from where something is imported from (vs doing something like `from unittest imort TestCase`, where you know exactly where `TestCase` has come from).

Alternatively, if you have a lot to import it can be easier to go with `import gene_annotation2bed as bed` or similar, then reference everything as `bed.convert_coordinates`
</blockquote></details>

Nice yeah changed to bed.function
___
*[`tests/test_gene_annotation2bed.py` line 189 at r2](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/4#-NpLqsYU1Wh5l_LArj-u:-NpZN1570qtW-3sd3M1t:b-nb1tqg) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/3f77e25e2e17e2b2d665e25b95a2dc099dc79314/tests/test_gene_annotation2bed.py#L189)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

I thiiiiink using `capsys` for capturing stdout / stderr in tests is more robust (although I dont remember where I read a good explanation but this is a good start: https://docs.pytest.org/en/7.1.x/how-to/capture-stdout-stderr.html )
</blockquote></details>

Nice that's a lot more streamlined now
___
*[`tests/test_gene_annotation2bed.py` line 218 at r2](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/4#-NpLr8gZAecANW9Scj5t:-NpTxvYE31Xhu_xVT6JD:brmvry9) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/3f77e25e2e17e2b2d665e25b95a2dc099dc79314/tests/test_gene_annotation2bed.py#L218)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

you don't actually use this, should it be in the `self.assertRaises`?
</blockquote></details>

updated to use expected output and the correct one.
___
*[`tests/test_igv_report.py` line 5 at r2](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/4#-NpLrWAb0SGCqdqVF1_P:-NpTxuOG5Qyu32hItSg-:bb7lgjf) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/3f77e25e2e17e2b2d665e25b95a2dc099dc79314/tests/test_igv_report.py#L5)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

is this still needed?
</blockquote></details>

nope

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 12 of 16 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/4)* status: 22 of 26 files reviewed, 2 unresolved discussions (waiting on @RSWilson1)

___
*[`tests/test_construct_vcf.py` line 189 at r3](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/4#-Np_-gMf60j8F9k0uVZ5:-Np_-gMf60j8F9k0uVZ6:b-c0tnsn) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/8fb63c268efc104a4d56775bdeed4d867ab25771/tests/test_construct_vcf.py#L189)):*
> ```Python
>             result_df = vcf_obj.fetch_nucleotides(row, self.reference_path)
> 
>     @pytest.mark.skipif(IN_GITHUB_ACTIONS, reason="Test doesn't work in Github Actions.")
> ```

why does this not work?

**Review by RSWilson1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/4)* status: 21 of 26 files reviewed, 1 unresolved discussion (waiting on @jethror1 and @RSWilson1)

___
*[`tests/test_construct_vcf.py` line 189 at r3](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/4#-Np_-gMf60j8F9k0uVZ5:-NpdKPf22vTOhSgYUCsj:b-js5j5m) ([raw file](https://github.com/eastgenomics/gene_annotation2bed/blob/8fb63c268efc104a4d56775bdeed4d867ab25771/tests/test_construct_vcf.py#L189)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

why does this not work?
</blockquote></details>

It requires the reference file to construct which I have now changed the yaml to pull in so it works now.

**Review by jethror1 — APPROVED** [review]
> Reviewed 3 of 16 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/gene_annotation2bed/4)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RSWilson1)

**Pull request merged**
